"""auto generate tables from models

Revision ID: 13347700f76c
Revises: 
Create Date: 2022-03-01 03:48:17.858647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13347700f76c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice_user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('frequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequence', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_name', sa.String(), nullable=False),
    sa.Column('address_wallet', sa.String(), nullable=False),
    sa.Column('category_request', sa.String(), nullable=False),
    sa.Column('id_user_choice_stat', sa.Integer(), nullable=False),
    sa.Column('id_frequence', sa.Integer(), nullable=False),
    sa.Column('result_stat', sa.String(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['id_frequence'], ['frequences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user_choice_stat'], ['choice_user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('users')
    op.drop_table('frequences')
    op.drop_table('choice_user_stats')
    # ### end Alembic commands ###
